### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by gavinelder**
I hate to be that person but these were flagged when I opened the project in an editor via corp linter the changes are. 

1) No empty lines at the beginning or end of a function
2) std imports must be in a separate group at the top
3) Simple var-declaration statements should use short assignments
4) Comment spacing
5) go imports alphabetical
6) go mod tidied and alphabetical

### CODE REVIEW

**Comment by grahamgilbert** [comment]
Which linter did you use? Without that it’s just going to happen again.

**Comment by groob** [comment]
Some of these edits look manual, but are things I would've counted as nits in a code review. 

Using ` := ` instead of `var someval = x` is usually the more accepted format.

**Comment by gavinelder** [comment]
Hi the output came from the following. 

https://github.com/mvdan/gofumpt with https://github.com/golangci/golangci-lint being used on strict mode.

**Comment by grahamgilbert** [comment]
@gavinelder Can you share the `.golangci.yaml` config used?

**Pull request merged**
