### PR TITLE
Add docs for systemd

### PR DESCRIPTION
**Pull request by gavinelder**
### Credit

The following was originally found on the [MicroMDMWiki](https://github.com/micromdm/micromdm/wiki/Using-MicroMDM-with-systemd) original contributions by [Groob](https://github.com/groob) & [Dan Falzon](https://github.com/danfalzon-sohonet)

### CODE REVIEW

**Comment by grahamgilbert** [comment]
Love this, but shouldn’t it be in the wiki?

**Comment by gavinelder** [comment]
Happy to do so but as the wiki doesn't exist yet I can't throw it in there. 

If you start it I can add there.

**Comment by grahamgilbert** [comment]
Wiki exists

**Comment by gavinelder** [comment]
Awesome, think it's actually a permissions issue as I can't create pages.

**Comment by grahamgilbert** [comment]
Try now

**Comment by gavinelder** [comment]
All good https://github.com/mdmdirector/mdmdirector/wiki/Systemd-configuration this can be closed.

**Pull request closed without merging**
