### PR TITLE
Fix/add contributor docs

### PR DESCRIPTION
**Pull request by bizzybits**
This PR was created to add additional support and technical documentation resources for **mdmdirector.**

In it I have added a new directory called `getting_involved_docs` which includes infrastructure and additional information for the curious user and developer community:

- `start_here.md` -> offers a welcome message and introduction to the project with links to the following docs

- `ISSUE_TEMPLATE` dir -> includes `bug.md` report template

- `community_standards.md` -> includes information about the agreed upon standards for this project

- `contribute.md` -> shows instructions on submitting bug reports, pull requests, and updating the `CHANGELOG.md`

- `sample_pr.md` -> template to add to PR

- `to_do.md` -> open list with opportunities to contribute to the project plus the skills needed for each task

I also installed a go pkg `git-chglog` which runs a go script that autogenerates a changelog for the project.
You can see the directory with .yaml files in `.chglog`, along with templates.
The main `CHANGELOG.md` file is updated given the steps listed in `contribute.md`.

The motivation behind these changes are to invite more developers into the project and provide a clearer engagement process.

### CODE REVIEW

**Review by grahamgilbert — COMMENTED** [review]
Could you ignore your .DS_Store file?

Also, GitHub supports [issue and PR templates natively](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates) - we should is those. This is a great start though!

**Comment by bizzybits** [comment]
Hi Graham! Appreciate your review! I have removed the .DS_Store and added it to the .gitignore. 
I will take a look at the docs you sent over and edit my PR. 👍 
Thanks!

**Comment by bizzybits** [comment]
Revised narrative on the contibutions page and removed the pr and bug templates. 
Happy Friday!

**Comment by grahamgilbert** [comment]
I still see a .DS_Store file here - could you remove it please?

What consumes the change log template? It looks like a go template. Is this some other tool? It doesn’t look like native GitHub functionality.

**Comment by grahamgilbert** [comment]
Bump @bizzybits

**Pull request closed without merging**
